spring.application.name=HeathCareBridge

server.port=8081
#configuration for database
spring.datasource.url =jdbc:postgresql://localhost:5432/healthcarebridge
spring.datasource.username=postgres
spring.datasource.password=Rohit@12
