spring.application.name=HeathCareBridge

server.port=8081
#configuration for database
spring.datasource.url =jdbc:postgresql://localhost:5432/healthcarebridge
spring.datasource.username=postgres
spring.datasource.password=Rohit@12

# jpa related configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true


# datasource initialization
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#logging related configuration
logging.level.org.springframework=DEBUG

#debugging transactional configuration
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.org.springframework.transaction.interceptor.TransactionInterceptor=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Jwt related configuration
spring.app.secretKey=MySecretKey848395094509869395965696dfghjkjhgffghjkgfthgutetrtuhuytf6tuy76r6t87t67tyiy6rf8t54r
spring.app.jwtExpirationMs=864000000
spring.app.jwtCookieName=Rp-ecommerceCookie