package com.Lifelink.HeathCareBridge.model;

public enum BloodComponent {
    CRYO_POOR_PLASMA,
    CRYOPRECIPITATE,
    FROZEN_PLASMA,
    PLATELETS,
    RED_BLOOD_CELLS,
    WHOLE_BLOOD,
    IRRADIATED_RED_BLOOD_CELLS,
    PLATELET_CONCENTRATED,
    PLATELET_RICH_PLASMA,
    SINGLE_DONOR_PLATELETS,
    SAGM_RED_BLOOD_CELLS,
    WASHED_RED_BLOOD_CELLS,
    SINGLE_DONOR_PLASMA,
    FROZEN_PLASMA_THERAPEUTIC_USE,
    FROZEN_PLASMA_LIQUID,
    FROZEN_PLASMA_LIQUID_THERAPEUTIC_USE
}
