name: deploy on ec2
on:
  workflow_dispatch:
jobs:
  deploy:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
     - name: sshing on ec2
       uses: appleboy/ssh-action@v1
       with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.HOST_USER }}
          command_timeout: 30m
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/health-care-bridge
            git pull origin main
            cd /home/ubuntu/health-care-bridge/HeathCareBridge
            docker compose up -d --build
