name: ci
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      defaults:
        run:
          working-directory: ./HeathCareBridge
      services:
        postgres:
          image: postgis/postgis:17-3.5
          ports:
            - 5432:5432
          env:
            POSTGRES_USER: testUser
            POSTGRES_PASSWORD: testPassword
            POSTGRES_DB: testDB
          options:
           --health-cmd "pg_isready"
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
      steps:
        - name: checkout the code
          uses: actions/checkout@v6
        - name: setting up java 21
          uses: actions/setup-java@v5
          with:
              distribution: 'temurin'
              java-version: '21'
              cache: 'maven'
        - name: build with maven
          run: mvn clean verify -Dspring.profiles.active=test
          env:
            DB_URL: jdbc:postgresql://localhost:5432/testDB
            DB_USERNAME: testUser
            DB_PASSWORD: testPassword
            adminEmail: dummy@gmail.com
            adminPassword: dummyPassword
            adminUsername: dummyUsername
            phoneNumber: +919089769000
            TELEGRAM_BOT_TOKEN: dummyToken
            BASE_AI_URL: http://localhost:9999
            AI_API_KEY: dummyKey
            COOKIE: dummyCookie
            JWT_SECRET: dummySecret
            AI_MODEL: dummyModel

